build_package: check for  arch packages
Some packages are not tied to a specific architecture, and specify 'any'
for the package arch. This will the package name also to contain -any-,
instead of the current architecture.

Try to find a package that has -any- when the arch specific package
cannot be found.

diff --git a/build_package b/build_package
--- a/build_package
+++ b/build_package
@@ -67,7 +67,18 @@ add_pkgs_to_repo ()
 
         for pkg in $packages
         do
-            local new_pkg_name="$pkg-$version-$rel-$arch.pkg.tar.xz"
+            local new_pkg_name=$(pkg_filename $pkg $arch)
+
+            if [[ ! -f $new_pkg_name ]]
+            then
+                new_pkg_name=$(pkg_filename $pkg any)
+
+                if [[ ! -f $new_pkg_name ]]
+                then
+                    error "Could not find package files for $pkg"
+                    exit 1
+                fi
+            fi
 
             remove_pkgs $repo_path/$pkg_arch $pkg
             copy_package $pkg_arch $new_pkg_name
@@ -116,6 +127,18 @@ sign_pkgs ()
     do
         msg2 $pkg
         file_name=$(pkg_filename $pkg $arch)
+
+        if [[ ! -f $file_name ]]
+        then
+            file_name=$(pkg_filename $pkg any)
+
+            if [[ ! -f $file_name ]]
+            then
+                error "Could not find package files for $pkg"
+                exit 1
+            fi
+        fi
+
         gpg --detach-sign --use-agent --no-armor "$file_name"  || exit 1
     done
 }
